### ISSUE TITLE
Spring Intilializr Haven't seen

### ISSUE THREAD

**Issue by minliuhua** [eltonsandre/intellij-spring-boot-helper#5]
![image](https://user-images.githubusercontent.com/65475189/184847861-273321f8-e52c-4eec-bb07-8e001defc92a.png)

![image](https://user-images.githubusercontent.com/65475189/184848278-2b7e2716-3275-438b-a3d8-3f33f78e5ee0.png)

**Comment by eltonsandre** [comment]
Hi @minliuhua 

The plugin corresponding to this repository is this [Spring Boot Helper](https://plugins.jetbrains.com/plugin/18622-spring-boot-helper).

If you install it, it is important to choose one of them, both do not coexist well, precisely because they are from the same fork, and generate conflicts.
